SELECT
	A2.CCMS_ID AS dc,
	A1.CCMS_ID AS cmr,
	ac.mpp_num
FROM
	SME.ACCOUNTS A1
INNER JOIN SME.ACCOUNTS A2 ON
	A1.PARENT_ID = A2.ID
	AND A2.DELETED = 0
INNER JOIN
(SELECT aui.ACCOUNT_ID FROM SCTID.ACCOUNTS_USERS AUi
	WHERE  AUi.DELETED = 0  GROUP BY aui.ACCOUNT_ID) AU ON
	AU.ACCOUNT_ID = A1.ID--LEFT JOIN SCTID.USERS U ON U.ID = AU.USER_ID AND U.DELETED=0
LEFT JOIN accounts_cstm ac
ON  a1.id=ac.id_c
WHERE A1.CCMS_LEVEL = 'S'
WITH ur