TRUNCATE TABLE CMRDC.${stagingTable} IMMEDIATE;
TRUNCATE TABLE CMRDC.PRODUCTS_IMAGE IMMEDIATE;
TRUNCATE TABLE CMRDC.USER_ACCOUNT_REL IMMEDIATE;
TRUNCATE TABLE CMRDC.USER_PRODUCT_REL IMMEDIATE;

--RULES_DATA_SS1 ——${ssTable}