--TRUNCATE TABLE CMRDC.${stagingTable} IMMEDIATE;
TRUNCATE TABLE CMRDC.PRODUCTS_IMAGE IMMEDIATE;
TRUNCATE TABLE CMRDC.${user_account} IMMEDIATE;
TRUNCATE TABLE CMRDC.${user_product} IMMEDIATE;

--RULES_DATA_SS1 ——${ssTable}