--TRUNCATE TABLE CMRDC.${stagingTable} IMMEDIATE;
TRUNCATE TABLE CMRDC.${product_image} IMMEDIATE;
TRUNCATE TABLE CMRDC.${user_account} IMMEDIATE;
TRUNCATE TABLE CMRDC.${user_product} IMMEDIATE;
TRUNCATE TABLE CMRDC.${dcCmrCcms} IMMEDIATE;

--RULES_DATA_SS1 ——${ssTable}